version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    network_mode: "host"
    volumes:
      - ./app_conf:/app/conf
      - ./app_sessions:/app/sessions
    restart: always